fredrikaverpil/neotest-golang

- lua/neotest-golang/init.lua
See comment in committed code.
> Simplify project root detection (better monorepo support)

- .github/workflows/test.yml
> Fix false positives in lua tests

- .github/workflows/format.yml
- .github/workflows/lint.yml
- .github/workflows/vuln.yml
- Makefile
> Add govulncheck

- .github/workflows/vuln.yml
- Makefile
- **fix(ci): move 'go vet' to linting**
- **feat(ci): run vuln checks on cron schedule**
> Run vuln checks on schedule

- lua/neotest-golang/ast.lua
- tests/go/positions_spec.lua
- tests/go/positions_test.go
- **refactor: break up queries**
- **feat: support table tests defined as in-loop anon structs**
> feat: support table tests defined in for loop

- lua/neotest-golang/cmd.lua
- lua/neotest-golang/parse.lua
- lua/neotest-golang/runspec_dir.lua
- lua/neotest-golang/runspec_file.lua
- lua/neotest-golang/runspec_test.lua
Found a few outdated things, unused variables, wrong namings causing confusion. Refactored and cleaned the context up a bit which is sent into the runspec. Probably fixed edge case bugs.
> refactor: runspec context

- lua/neotest-golang/cmd.lua
- lua/neotest-golang/init.lua
- lua/neotest-golang/json.lua
- lua/neotest-golang/parse.lua
- lua/neotest-golang/runspec_dir.lua
- lua/neotest-golang/runspec_file.lua
- lua/neotest-golang/runspec_test.lua
> feat: run all tests in file with one 'go test' command

- lua/neotest-golang/parse.lua
- lua/neotest-golang/path.lua
- lua/neotest-golang/runspec_dir.lua
- lua/neotest-golang/runspec_file.lua
- **refactor: remove unused**
- **refactor: move logic into new path lib**
> refactor: move shared logic into new path lib

- .github/dependabot.yml
https://github.com/dependabot/dependabot-core/issues/2178#issuecomment-2213126037
> ci: workaround for dependabot dir wildcard not working yet

- README.md
As requested :smile: 
I'm off for a while, but feel free to make adjustments.
> docs(readme): add rocks.nvim install instructions

- README.md
Would appreciate if someone using Nix / Home manager can help me out and see if this looks ok!
> docs(README): add nix config example

- README.md
@augbed if you have time, please have a look. Does this look ok to you?
> docs: add a note on build tags

- lua/neotest-golang/features/testify/query.lua
- lua/neotest-golang/query.lua
- tests/go/positions_test.go
- tests/unit/golist_spec.lua
> fix: do not detect TestMain as test function

- .github/workflows/test.yml
* Aims to track, and once passing, fix: #180
* I opened an issue with https://github.com/nvim-neotest/neotest/issues/452
> ci(test): enable nightly neovim again

- README.md
- lua/neotest-golang/features/dap/init.lua
- lua/neotest-golang/init.lua
- lua/neotest-golang/runspec/file.lua
- lua/neotest-golang/runspec/test.lua
closes #203 as this adds some minor refactoring, cleanups, docs.
Thank you @hown3d! ❤️ 
I added some more commits to your work.
> feat(dap): add support for debugging tests in a file

- lua/neotest-golang/runspec/dir.lua
- lua/neotest-golang/runspec/file.lua
- lua/neotest-golang/runspec/namespace.lua
- lua/neotest-golang/runspec/test.lua
This could potentially also help the long-running `go list` mentioned in https://github.com/fredrikaverpil/neotest-golang/pull/245
> perf: more efficient 'go list' $cwd

- README.md
- lua/neotest-golang/health.lua
- lua/neotest-golang/lib/cmd.lua
- lua/neotest-golang/lib/init.lua
- lua/neotest-golang/lib/json.lua
- lua/neotest-golang/lib/sanitize.lua
- lua/neotest-golang/options.lua
- lua/neotest-golang/process.lua
- tests/go/internal/sanitization/sanitize_test.go
- tests/go/lookup_spec.lua
- tests/unit/options_spec.lua
> feat: add option to sanitize test execution output

- .github/workflows/format.yml
- .github/workflows/lint.yml
- .github/workflows/test.yml
- .github/workflows/vuln.yml
> ci: add ability to run next version of go

- lua/neotest-golang/process.lua
> fix: missing output from test execution

- .github/workflows/sync.yml
- .github/workflows/test.yml
- .github/workflows/unmanaged-lua.yml
This PR syncs the GitHub repo with CI workflows from the [fredrikaverpil/github](https://github.com/fredrikaverpil/github) repository.
> ci(workflows): sync with fredrikaverpil/github

- .github/dependabot.yml
Reverts fredrikaverpil/neotest-golang#330
> ci(dependabot): revert "sync with fredrikaverpil/github"

- lua/neotest-golang/features/testify/query.lua
This adds support for treesitter's main branch: https://github.com/nvim-treesitter/nvim-treesitter/tree/main
> feat: treesitter main branch support (for testify)

- docs/config.md
- docs/recipes.md
- lua/neotest-golang/options.lua
- lua/neotest-golang/runspec/dir.lua
- lua/neotest-golang/runspec/file.lua
- lua/neotest-golang/runspec/namespace.lua
- lua/neotest-golang/runspec/test.lua
- tests/unit/options_spec.lua
Ref #359 
Hey! This is my rather simple implementation for the env option. Please, feel free to let me know if I should add more tests.
> feat: add support for passing env vars to neotest runspec

- lua/neotest-golang/health.lua
- **chore: os info**
- **chore: better config output**
> chore: better checkhealth output, added os information
