- README.md
- lua/neotest-golang/init.lua
Ideally, we won't need the `gotestsum` dependency.
- Replace the dependency on `gotestsum` by running `go test`.
- Erase the file, written by Neotest, which contains the stdout/stderr test command output, at the end of the test's JSON parsing. This file erasing was key to avoid getting JSON spewed into the test output panel, as described in https://github.com/nvim-neotest/neotest/issues/391.
- Remove mentioning of `gotestsum` from README.
- Changed various inline notes.
- Comment out printouts of non-JSON lines for now (will have to add a log file or similar later).
- Gotestsum could be added back in as an optional test runner, as an alternative to `go test`. But I think most users are looking to use as few dependencies as possible. 🎉 
- At this point, I wish I had tests, so this is …
> Remove need for gotestsum

- README.md
- lua/neotest-golang/init.lua
Blocked by https://github.com/leoluz/nvim-dap-go/pull/81
- Auto-setup nvim-dap-go and provide it with a `cwd` for successful `dlv` debugging of test in Go sub-project.
- Add configuration options for nvim-dap-go.
- Resets nvim-dap-go inbetween test debug sessions, so to avoid a "sticky" `cwd`.
Needs overall cleanup and refactoring to make the whole project more readable and testable... but that will come later.
> Leverage nvim-dap-go for test debugging

- lua/neotest-golang/convert.lua
- lua/neotest-golang/init.lua
- tests/go/main.go
- tests/go/positions.go
- tests/go/positions_spec.lua
- tests/go/testname_spec.lua
- tests/go/testname_test.go
This also starts adding tests.
> Allow single quotes in test name

- lua/neotest-golang/init.lua
> Fix: do not include file/lineno in error

- lua/neotest-golang/ast.lua
- lua/neotest-golang/convert.lua
- lua/neotest-golang/init.lua
- lua/neotest-golang/json.lua
- lua/neotest-golang/options.lua
- lua/neotest-golang/results_test.lua
- lua/neotest-golang/runspec_file.lua
- lua/neotest-golang/runspec_test.lua
- lua/neotest-golang/utils.lua
- tests/go/testname_spec.lua
- tests/go/testname_test.go
This prepares for supporting better testing and future features, such as test execution per directory or file (not only on a per-test basis).
There _should_ be no change in behaviour or breakage!
> Refactor: Split up files and functions

- lua/neotest-golang/init.lua
- lua/neotest-golang/options.lua
- lua/neotest-golang/runspec_test.lua
- tests/unit/options_spec.lua
Makes it a bit more readable/maintainable.
> Refactor options and defaults

- README.md
- lua/neotest-golang/convert.lua
- lua/neotest-golang/init.lua
- lua/neotest-golang/json.lua
- lua/neotest-golang/options.lua
- lua/neotest-golang/results_dir.lua
- lua/neotest-golang/results_test.lua
- lua/neotest-golang/runspec_dir.lua
- lua/neotest-golang/runspec_file.lua
- lua/neotest-golang/runspec_test.lua
- tests/go/testname_spec.lua
- tests/go/testname_test.go
- tests/unit/json_spec.lua
- tests/unit/options_spec.lua
This adds substantial performance improvements on being able to run all tests in
a Go project using one 'go test' command, instead of executing on a per-test
basis.
Either run all tests in the entire test suite (given that you have a `go.mod` in your $cwd):
```lua
require("neotest").run.run({ suite = true })
```
Or select a directory in the Neotest summary window, and hit `r` to execute the tests
in that Go package.
> Add support for position type 'dir'

- lua/neotest-golang/convert.lua
- lua/neotest-golang/runspec_test.lua
- tests/go/testname_spec.lua
- tests/go/testname_test.go
This has led to false positives when running a single test (or a file of tests).
> Go test regexp pattern does not escape parenthesis

- README.md
- lua/neotest-golang/options.lua
- lua/neotest-golang/results_test.lua
- tests/unit/options_spec.lua
This can happen if you e.g. are using testify. Fixes #40.
https://github.com/fredrikaverpil/neotest-golang/assets/994357/7d17e740-8594-4595-a327-6ca9d3d4352e
> Warn if test was not executed

- lua/neotest-golang/options.lua
- lua/neotest-golang/results_dir.lua
- tests/unit/options_spec.lua
This notification can be rather chatty in certain projects, so let's add a new dev-type option which can be used to enable it. The default is to have this disabled, as it will show in the test summary window that the test(s) were skipped.
The purpose of this notification is to try and catch bugs for when comparing a package/test from the `go test` test output with Neotest's position id.
> Add debug-level notification when package/test cannot be identified from test output

- README.md
- lua/neotest-golang/options.lua
- tests/unit/options_spec.lua
I'm removing the timeout as it's difficult to provide a sane default here. Everyone has different needs.
> fix: remove timeout from default args

- lua/neotest-golang/init.lua
- lua/neotest-golang/options.lua
> fix: options not returned

- lua/neotest-golang/convert.lua
Having a test like this would result it not being run, and skipped by neotest-golang as the output would include "no tests to run":
```go
package main
import "testing"
// A dummy test, just to assert that Go tests can run.
func TestNames(t *testing.T) {
t.Run("Brackets [1] (2) {3} are ok", func(t *testing.T) {
if Add(1, 2) != 3 {
t.Fail()
}
})
}
```
```
=== RUN   TestNames
--- PASS: TestNames (0.00s)
testing: warning: no tests to run
PASS
coverage: 0.0% of statements
ok      github.com/fredrikaverpil/neotest-golang        1.425s  coverage: 0.0% of statements [no tests to run]
```
Escape the brackets. Now the test runs fine.
> fix: escaping of []{} brackets were missing

- lua/neotest-golang/ast.lua
By mistake, I added this in ...
Please follow the POC in #58 instead.
> fix: remove test suite AST-detection (still in POC)

- lua/neotest-golang/parse.lua
Shouldn't attempt to parse any test output when debugging a test.
> fix: dap error

- lua/neotest-golang/cmd.lua
- lua/neotest-golang/dap.lua
- lua/neotest-golang/init.lua
- lua/neotest-golang/options.lua
- lua/neotest-golang/parse.lua
- lua/neotest-golang/runspec_dir.lua
- lua/neotest-golang/runspec_file.lua
- lua/neotest-golang/runspec_test.lua
- tests/unit/options_spec.lua
This is just me playing around with using `gotestsum` so output is readable when attaching to long-running test (hotkey `a` in the test summary window), like an entire test suite.
This can allow nice output to be shown (when attached) as tests are running. Under the hood, neotest-golang will still  parse the JSON output.
To do:
- Clean up and refactoring, so command arguments can be controlled nicely and intuitively.
- If `gotestsum` is chosen as "test runner", verify it indeed is on `$PATH` or throw error (possibly fall back to `go test`).
> feat: initial gotestsum support and larger refactoring

- lua/neotest-golang/cmd.lua
- lua/neotest-golang/runspec_file.lua
- **refactor: move test name fetching**
- **fix: escape regex characters in test name**
> fix: escape regex characters in test name

- lua/neotest-golang/path.lua
Fix #103
```lua
{
"nvim-neotest/neotest",
ft = { "go" },
dependencies = {
{
"fredrikaverpil/neotest-golang",
branch = "fix/expand-upwards-search",  -- ADD THIS
},
},
opts = function(_, opts)
opts.adapters = opts.adapters or {}
opts.adapters["neotest-golang"] = {
dap_go_enabled = true,
}
end,
},
```
> fix: search for go.mod up until home folder

- lua/neotest-golang/lib/init.lua
- lua/neotest-golang/lib/string.lua
- lua/neotest-golang/process.lua
> fix: include sub-test output in test output

- .github/DISCUSSION_TEMPLATE/configuration.yml
- README.md
- lua/neotest-golang/features/testify/tree_modification.lua
- lua/neotest-golang/init.lua
- lua/neotest-golang/lib/cmd.lua
- lua/neotest-golang/lib/json.lua
- lua/neotest-golang/logging.lua
- lua/neotest-golang/options.lua
- lua/neotest-golang/process.lua
- lua/neotest-golang/runspec/dir.lua
- tests/unit/options_spec.lua
After having [given this some thought](https://github.com/nvim-neotest/neotest/discussions/422), I'm adding a logger which piggybacks on / reuses the neotest logger.
This also removes the unused option `warn_test_not_executed`.
> feat: add logger

- lua/neotest-golang/features/dap/init.lua
- lua/neotest-golang/runspec/test.lua
- **fix: show better error when DAP is not configured properly** (related to https://github.com/fredrikaverpil/neotest-golang/discussions/140)
- **fix: regex characters applied twice**
> fix(dap): show config error, remove excessive regex characters from test name

- README.md
- lua/neotest-golang/lib/cmd.lua
- lua/neotest-golang/lib/convert.lua
- lua/neotest-golang/logging.lua
- lua/neotest-golang/options.lua
- lua/neotest-golang/process.lua
- lua/neotest-golang/runspec/dir.lua
- lua/neotest-golang/runspec/file.lua
- lua/neotest-golang/utils/buffer.lua
- lua/neotest-golang/utils/init.lua
- tests/unit/options_spec.lua
This adds more logging, so to make it easier to debug adapter setup issues. I've also added a few performance optimizations so not to excessively transform tables/messages when logging is not enabled.
> chore: log more

- README.md
- lua/neotest-golang/options.lua
- lua/neotest-golang/runspec/test.lua
- tests/unit/options_spec.lua
It's sufficient to just make sure to have the dap-go plugin installed.
If the plugin is not installed, this will be shown in `:checkhealth neotest-golang` and as an error notification in Neovim if you try to debug a test.
This is technically not breaking backwards compatibility but will leave an unused option dangling in user configs. I could add a warning that will pop up about this, but I'm not sure it's really that important and worthy of the noise...
> chore: remove option required to enable dap

- lua/neotest-golang/logging.lua
- lua/neotest-golang/process.lua
- **fix: log tables using linebreaks and tabs for easier reading**
- **chore(logging): enable more debug logging**
> chore: more debug logging

- lua/neotest-golang/lib/cmd.lua
Tests would always be reported as skipped with the "not associated" message.
Not sure how to pinpoint the exact cause of this issue but it happens on my personal setup (WSL Arch with Windows Terminal Canary, if that helps).
`go list` output from log file before this change:
```
...
DEBUG | 2024-08-15T21:36:45Z+0700 | ...uddin/code/neotest-golang/lua/neotest-golang/logging.lua:47 | [neotest-golang] Running Go list: go list -json ./... in /home/miduddin/code/test_go
INFO | 2024-08-15T21:36:45Z+0700 | ...uddin/code/neotest-golang/lua/neotest-golang/logging.lua:59 | [neotest-golang] Go list output:  ]9;9;\\wsl.localhost\arch2\home\miduddin\code\test_go\{ "Dir": "/home/miduddin/code/test_go", "ImportPath": "localhost/testgo", "Name": "main", "Target": …
```
> fix!: broken 'go list' report on some systems

- lua/neotest-golang/utils/buffer.lua
When running `:lua require("neotest-golang.utils.buffer").filter("[neotest-golang]")`, the filter will not keep newlines for the log entry.
Before:
```
DEBUG | 2024-09-07T17:28:13Z+0200 | ...ode/public/neotest-golang/lua/neotest-golang/logging.lua:47 | [neotest-golang] DAP strategy used: {
DEBUG | 2024-09-07T17:28:13Z+0200 | ...ode/public/neotest-golang/lua/neotest-golang/logging.lua:47 | [neotest-golang] Provided dap_go_opts for DAP:  {
```
After:
```
DEBUG | 2024-09-07T17:31:39Z+0200 | ...ode/public/neotest-golang/lua/neotest-golang/logging.lua:47 | [neotest-golang] DAP strategy used: {
args = { "-test.run", "^TestTopLevelWithSubTest/SubTest$" },
buildFlags = { "-tags=integration" },
mode = "test",
name = "Neotest-golang",
program = "${fileDirname}",
request = "launch",
type = "go"
} …
```
> fix: keep all lines until next log entry

- README.md
- lua/neotest-golang/features/dap/init.lua
Build tags are not propagated to the internal dap-go config.
This adds support for passing build flags to delve:
```lua
return {
{
"nvim-neotest/neotest",
config = function()
require("neotest").setup({
adapters = {
require("neotest-golang")({
go_test_args = { "-count=1", "-tags=integration" },
go_list_args = { "-tags=integration" },
dap_go_opts = {
delve = {
build_flags = { "-tags=integration" },
},
},
}),
},
})
end,
},
}
```
- When constructing the internal dap-go launch configuration, check if
`delve.build_flags` was provided in neotest-golang opts.
- Update docs with example.
> feat: use build flags for delve in dap-go config

- lua/neotest-golang/init.lua
- lua/neotest-golang/lib/cmd.lua
- lua/neotest-golang/lib/json.lua
- lua/neotest-golang/process.lua
- lua/neotest-golang/runspec/dir.lua
- lua/neotest-golang/runspec/file.lua
- lua/neotest-golang/runspec/namespace.lua
- lua/neotest-golang/runspec/test.lua
fixes #169
* When there's e.g. a compilation error, this is not properly handled. Often the error shown is "Test(s) not associated" which is not very clear.
- Make `go list` failure show as Neotest test failure.
- Make `go test` failure show as a Neotest test failure. Supports both `go` and `gotestsum` runners.
- Added ability to pass various errors onto the RunSpec context.
```lua
{
"fredrikaverpil/neotest-golang",
branch = "output-on-failure",
},
```
> feat: show compilation failure as test output

- README.md
- lua/neotest-golang/lib/cmd.lua
- lua/neotest-golang/options.lua
- tests/unit/options_spec.lua
Fixes #186
Some users need to dynamically generate the `go test` command on each test run.
Supply a function instead of a table as `go test` args:
Please give something like this a try:
```lua
return {
{
"nvim-neotest/neotest",
dependencies = {
"nvim-neotest/nvim-nio",
"nvim-lua/plenary.nvim",
"antoinemadec/FixCursorHold.nvim",
"nvim-treesitter/nvim-treesitter",
{
"fredrikaverpil/neotest-golang", -- Installation
branch = "args-function", -- Custom branch
},
},
config = function()
local opts = { -- Specify configuration
go_test_args = function()
-- Place your custom logic here for the 'go test' args
return {
"-v",
"-race",
"-count=1",
"-coverprofile=" .. vim.fn.getcwd() .. "/coverage.out",
}
end,
}
require("neotest").setup({
adapters = {
require("neotest-golang")(opts), -- Apply …
```
> feat: add ability to pass args as function instead of table

- README.md
- lua/neotest-golang/features/dap/init.lua
- tests/unit/options_spec.lua
For `go test` and `go list`, args can be provided as functions. But I didn't add this for the dap-go opts, where you might have similar needs (e.g. if you need to compute the build tags in runtime rather than on adapter initialization).
Add capability to pass in function for dap-go.
> feat(dap): pass dap-go opts as function

- README.md
- lua/neotest-golang/health.lua
- lua/neotest-golang/options.lua
- tests/unit/options_spec.lua
This adds documentation around running tests using [`gotestsum`](https://github.com/gotestyourself/gotestsum), which is already implemented in the `main` branch.
My original plan was to research output streaming before exposing the capability of configuring `gotestsum`, because it could end up dictating how the configuration around it would be like. But #149 sped up this process a bit, as it seems like a requirement on Windows with Powershell, hence this PR. However, I'll still keep this in draft for now, as I'm still not 100% sure about how I want `gotestsum` to be configured. There might also be a need to support custom test runners which could affect how configuration around `goteststum` and the default `go` would look like. All in all, this PR adds transparency on the subject.
> feat: gotestsum

- lua/neotest-golang/features/dap/init.lua
- lua/neotest-golang/runspec/test.lua
Currently when trying to debug tests via the Neotest Summary panel, the generated `dap_configuration` is not correct.
The variable `fileDirname` is expanded in nvim-dap as `vim.fn.expand("%:p:h")`
See https://github.com/mfussenegger/nvim-dap/blob/7ff6936010b7222fea2caea0f67ed77f1b7c60dd/lua/dap.lua#L338-L340
When the focus is on the summary panel, this returns the current working directory. 
Since we already know the exact path to the testfile by neotests positions, there's no need to rely on the information about the current window returned by `vim.fn.expand` function present in the dap client.
> fix(dap): use test filepath from neotest positions

- README.md
- lua/neotest-golang/options.lua
- lua/neotest-golang/process.lua
- tests/unit/options_spec.lua
Hi @fredrikaverpil  this is what I came up with. I have also updated the documentation. This option is false by default.
I would like to add a screenshot of how it looks but it seems that I don't have access to the assets folder?
Also, I haven't included tests for this, not sure if it is expected for this?
Please let me know if it follows the conventions and it is idiomatic, as I said I don't have experience with Lua and plugin development. The changes are very small, so not sure if I can get much feedback from it 😄 
Example of how it looks:
> feat: test output color

- lua/neotest-golang/health.lua
See https://github.com/golang/go/issues/9918 for more details.
Note that this is not applicable on macOS since go 1.20.
> feat(checkhealth): add check for CGO_ENABLED and -race arg

- lua/neotest-golang/lib/cmd.lua
- lua/neotest-golang/process.lua
- tests/go/subpackage/subpackage_test.go
- tests/go/testify/lookup_spec.lua
> feat: show build error in test output

- README.md
- lua/neotest-golang/features/dap/dap_go.lua
- lua/neotest-golang/features/dap/dap_manual.lua
- lua/neotest-golang/features/dap/init.lua
- lua/neotest-golang/options.lua
- tests/unit/options_spec.lua
Hello! I have a nvim config that contains a many of DAP configurations for some languages, also for golang. I don't want to install additional plugin special for debugging go apps or tests (this breaks a consistency of my config). I setup own DAP configuration for this and wanna use it to debug tests with your plugin.
> feat: using DAP without nvim-dap-go

- lua/neotest-golang/query.lua
- tests/go/positions_spec.lua
- tests/go/positions_test.go
> feat: table test inline struct loop, not keyed

- lua/neotest-golang/runspec/dir.lua
- tests/go/lookup_spec.lua
- tests/go/subpackage/subpackage2/subpackage2_test.go
- tests/go/subpackage/subpackage2/subpackage3/subpackage3_test.go
- tests/go/subpackage/subpackage_test.go
The current implementation did _not_ take into account:
* Recursively run tests for given package (in sub-packages).
* If no exact correlation was found between folder path and package import path, a search for sub-packages is conducted. The result can be used for inferring a proper package import path.
Huge thanks to @damoye for uncovering this rather large bug! ❤️ 
* Introduce two search strategies for correlating the selected folderpath with a package import path.
* Append `/...` at the end of the package import path.
___
fixes: #228
> fix: recursively run tests for dir

- lua/neotest-golang/query.lua
- tests/go/positions_spec.lua
- tests/go/positions_test.go
Ignore structs which are not being used as test tables.
For example, here "1" and "2" are reported as test examples:
```go
func TestStruct(t *testing.T) {
type item struct {
id   string
name string
}
items := []item{
{"1", "one"},
{"2", "two"},
}
for _, i := range items {
if i.id == "" {
t.Fail()
}
}
}
```
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
> fix: false positives on structs

- lua/neotest-golang/query.lua
- tests/go/internal/operand/operand_test.go
- tests/go/lookup_spec.lua
- tests/unit/golist_spec.lua
Turns out that `x.Run`, `router.Run`, `gin.Engine.Run()` was detected as tests.
Tighten up the tree-sitter query so to only look for `t.Run`.
> fix: only detect t.Run

- lua/neotest-golang/lib/json.lua
Use the faster lua implementation, without the overhead of the vimscript wrapper.
Isolating this change from #245
> perf: vim.fn.json_decode -> vim.json.decode

- lua/neotest-golang/lib/cmd.lua
- tests/go/internal/notest/notest.go
- tests/go/internal/two/one_test.go
- tests/go/internal/two/two_test.go
- tests/go/lookup_spec.lua
- tests/unit/golist_spec.lua
Although this might add some complexity and template execution, this can substantially reduce the JSON payload size from `go list`. This should mean that `vim.json.decode` won't have as much to do and hopefully this would be a performance gain on huge monorepos.
Related: #245
> perf: lower 'go list' JSON payload size

- lua/neotest-golang/lib/cmd.lua
It doesn't properly fix the underlying problem described in #276 but at least the adapter won't crash on Windows now.
> fix: temporary fix for 'go list -json -f ...' on windows

- lua/neotest-golang/features/testify/query.lua
- lua/neotest-golang/query.lua
- tests/go/internal/testify/positions_spec.lua
- tests/go/internal/testify/positions_test.go
As brought up in #275, the ability to use operand `s` in `s.Run` was removed by mistake in commit bd8e69ea606237c5e441f72ccf67fa774858b5dd.
I'm here bringing it back. However, I'm not sure if table tests can be supported easily. At least it will be handled, separately in #280
> fix: testify subtest operand not recognized

- lua/neotest-golang/query.lua
- **chore: format queries for easier reading/grokking**
- **fix: move match inside field scope for easier reading**
> chore: query formatting for easier reading/grokking

- .github/workflows/format.yml
- .github/workflows/test.yml
Running `go list` on Windows is flaky for some reason. Seems to timeout
testing etc. Disabling here and can be enabled when needed.
> ci: skip windows

- lua/neotest-golang/features/dap/dap_go.lua
I wasn't getting any logs on my repl, adding outputMode=remote fixed the problem.
Based on the following PR of nvim-dap-go: [PR link](https://github.com/leoluz/nvim-dap-go/pull/109)
> fix: missing outputs while debugging tests

- docs/trouble.md
To get faster feedback, I normally use `-vet="off"` in a shell. Placing that in the list of args cased the the "no tests" error. But passing them as `-vet=off` did the trick - so I'd just share the experience :)
I guess it's because it's the shell itself that interprets the command line, that handles the `"`s, so `go test` sees the value without `"`, so I just added that explanation for context.
> Add additional possible error cause

- lua/neotest-golang/lib/convert.lua
- tests/go/internal/testname/testname_spec.lua
- tests/go/internal/testname/testname_test.go
Solves https://github.com/fredrikaverpil/neotest-golang/issues/339
> fix(convert): correct regex passed to go test -run for single test execution

- lua/neotest-golang/process.lua
With go 1.24, new build falure information is part of `go test -json`. By reading this information, more accurate build error messages can be shown.
Add to the existing error handling, build failure messages.
> feat: better build error detection (go 1.24)

- .github/workflows/luarocks.yml
The luarocks deployment keeps getting triggered twice when releasing, causing this status:
> ci: avoid duplicate triggers

- spec/bootstrap.lua
- spec/minimal_init.lua
This cleans up and conforms the bootstrap (one-time) and init (per-test)
scripts. Additions involves making sure we are placing the adapter and
plugins on runtimepath. Plugins are also added to packpath.
> fix(init): fixes to bootstrap and minimal_init
